In [1]:
import numpy as np
import pandas as pd

In [2]:
data1 = pd.read_csv('LDAP.csv')

D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
data1.shape

(2113234, 88)

In [4]:
data1 = data1.sample(8000)

In [5]:
data1.shape

(8000, 88)

In [9]:
data2 = pd.read_csv('MSSQL.csv')

C:\Users\labuser.ITS\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [10]:
data2 = data2.sample(8000)

In [13]:
data3 = pd.read_csv('NetBIOS.csv')

In [14]:
data3 = data3.sample(8000)

In [16]:
data4 = pd.read_csv('Portmap.csv')

In [18]:
data4 = data4.sample(8000)

In [19]:
data5 = pd.read_csv('Syn.csv')

In [20]:
data5 = data5.sample(8000)

In [21]:
data6 = pd.read_csv('UDP.csv')

In [22]:
data6 = data6.sample(8000)

In [23]:
data7 = pd.read_csv('UDPLag.csv')

In [24]:
data7 = data7.sample(8000)

In [25]:
data = pd.concat([data1,data2,data3,data4,data5,data6,data7], ignore_index = True)

In [26]:
data.shape

(56000, 88)

In [27]:
data.columns

Index(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Len

In [28]:
data[' Label'].value_counts()

Syn        14623
UDP         9214
NetBIOS     8754
MSSQL       8018
Portmap     7831
LDAP        7236
BENIGN       302
UDPLag        22
Name:  Label, dtype: int64

In [29]:
data = data.drop(['Unnamed: 0'],axis = 1)

In [67]:
data = data.drop(['SimillarHTTP'],axis = 1)

In [68]:
data.columns

Index(['Flow ID', ' Source IP', ' Source Port', ' Destination IP',
       ' Destination Port', ' Protocol', ' Timestamp', ' Flow Duration',
       ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Pa

In [8]:
df = data1.copy()
cat_columns = df.select_dtypes(['object']).columns
cat_columns

Index(['Flow ID', ' Source IP', ' Destination IP', ' Timestamp',
       'SimillarHTTP', ' Label'],
      dtype='object')

In [9]:
df[cat_columns] = df[cat_columns].astype('category')
df[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)
df
data = df
data.dtypes

Unnamed: 0           int64
Flow ID              int16
 Source IP            int8
 Source Port         int64
 Destination IP       int8
                    ...   
 Idle Max          float64
 Idle Min          float64
SimillarHTTP          int8
 Inbound             int64
 Label                int8
Length: 88, dtype: object

In [69]:
data_real = data.replace(np.inf, np.nan)

In [70]:
data_real.isnull().sum().sum()

0

In [71]:
data_df = data_real.dropna(axis=0)

In [72]:
data_df.isnull().sum().sum()

0

In [73]:
df = data_df.copy()
cat_columns = df.select_dtypes(['object']).columns
cat_columns

Index([], dtype='object')

In [74]:
df[cat_columns] = df[cat_columns].astype('category')
df[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)
df
data = df
data.dtypes

Flow ID                int32
 Source IP              int8
 Source Port           int64
 Destination IP         int8
 Destination Port      int64
                      ...   
 Idle Std            float64
 Idle Max            float64
 Idle Min            float64
 Inbound               int64
 Label                  int8
Length: 86, dtype: object

In [98]:
data[' Label'].value_counts()

5    13544
6     9065
3     8426
2     7748
4     7454
1     7064
0      294
7       22
Name:  Label, dtype: int64

In [100]:
data= data.sample(n=len(data), random_state=1)

In [103]:
from imblearn.over_sampling import SMOTE 

In [105]:
smt = SMOTE()
X = data.iloc[:, 0:-1].values
y = data.iloc[:, -1].values
X, y = smt.fit_resample(X, y)

In [106]:
aa=np.bincount(y)
aa

array([13544, 13544, 13544, 13544, 13544, 13544, 13544, 13544],
      dtype=int64)

In [107]:
print('length of the dataset now after balance the dataset', len(X))

length of the dataset now after balance the dataset 108352


In [108]:
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
X= standardScaler.fit_transform(X)
X

array([[ 1.36400838, -0.45976469, -1.06850679, ..., -0.1669076 ,
        -0.15008422,  0.44536321],
       [-1.53327731, -0.45976469, -0.22818827, ..., -0.1669076 ,
        -0.15008422,  0.44536321],
       [-0.28964026, -0.45976469, -1.08521778, ..., -0.1669076 ,
        -0.15008422,  0.44536321],
       ...,
       [-1.17091808, -0.45976469,  0.3656485 , ..., -0.1669076 ,
        -0.15008422,  0.44536321],
       [-0.77469309,  2.0369576 ,  0.69500946, ..., -0.1669076 ,
        -0.15008422, -2.49675952],
       [-1.0450682 ,  0.91230415,  1.02570849, ..., -0.1669076 ,
        -0.15008422, -1.17147458]])

In [79]:
from sklearn.model_selection import train_test_split

In [109]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.67, test_size = 0.33, random_state = 42)

In [110]:
X_train.shape

(72595, 85)

In [111]:
X_test.shape

(35757, 85)

In [112]:
#CNN

In [113]:
#CNN algorithm libraries
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Conv1D, GlobalMaxPooling1D


#for evaluation of trained algorithms 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [114]:
from tensorflow.keras.optimizers import RMSprop

In [115]:
model = Sequential()

In [116]:
model.add(Dense(512, input_dim=85))

In [117]:
model.add(Activation('relu'))
model.add(Dropout(0.01))

In [118]:
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.01))

In [119]:
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.01))

In [120]:
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.01))
model.add(Dense(13, activation="softmax"))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_13 (Dense)            (None, 512)               44032     
                                                                 
 activation_11 (Activation)  (None, 512)               0         
                                                                 
 dropout_10 (Dropout)        (None, 512)               0         
                                                                 
 dense_14 (Dense)            (None, 256)               131328    
                                                                 
 activation_12 (Activation)  (None, 256)               0         
                                                                 
 dropout_11 (Dropout)        (None, 256)               0         
                                                                 
 dense_15 (Dense)            (None, 128)              

In [121]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['acc'])

In [122]:
model.summary()
model.compile(loss='sparse_categorical_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_13 (Dense)            (None, 512)               44032     
                                                                 
 activation_11 (Activation)  (None, 512)               0         
                                                                 
 dropout_10 (Dropout)        (None, 512)               0         
                                                                 
 dense_14 (Dense)            (None, 256)               131328    
                                                                 
 activation_12 (Activation)  (None, 256)               0         
                                                                 
 dropout_11 (Dropout)        (None, 256)               0         
                                                                 
 dense_15 (Dense)            (None, 128)              

In [123]:
model.fit(X_train,y_train,batch_size=20,epochs=20,
          validation_split=0.1)

Epoch 1/20
3267/3267 [==============================] - 11s 3ms/step - loss: 0.1306 - accuracy: 0.9589 - val_loss: 0.0693 - val_accuracy: 0.9820
Epoch 2/20
3267/3267 [==============================] - 10s 3ms/step - loss: 0.0942 - accuracy: 0.9799 - val_loss: 0.1003 - val_accuracy: 0.9802
Epoch 3/20
3267/3267 [==============================] - 11s 3ms/step - loss: 0.1097 - accuracy: 0.9809 - val_loss: 0.0829 - val_accuracy: 0.9759
Epoch 4/20
3267/3267 [==============================] - 13s 4ms/step - loss: 0.1279 - accuracy: 0.9820 - val_loss: 0.2346 - val_accuracy: 0.9658
Epoch 5/20
3267/3267 [==============================] - 11s 3ms/step - loss: 0.1480 - accuracy: 0.9828 - val_loss: 0.1964 - val_accuracy: 0.9635
Epoch 6/20
3267/3267 [==============================] - 11s 3ms/step - loss: 0.1272 - accuracy: 0.9836 - val_loss: 0.1631 - val_accuracy: 0.9876
Epoch 7/20
3267/3267 [==============================] - 11s 3ms/step - loss: 0.1418 - accuracy: 0.9844 - val_loss: 0.1121 - val_ac

In [124]:
accr = model.evaluate(X_test,y_test)

1118/1118 [==============================] - 2s 2ms/step - loss: 2.6188 - accuracy: 0.9929


In [125]:
y_pred = model.predict(X_test)
y_pred=y_pred.argmax(axis=1)
print('Test set\n  Accuracy: {:0.2f}'.format(accr[1]))

Test set
  Accuracy: 0.99


In [126]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [129]:
rf_conf_mat = confusion_matrix(y_test, y_pred)
print("CNN Confusion: \n", rf_conf_mat)

CNN Confusion: 
 [[4513    0    0    0    2    0    0    0]
 [   2 4429    2    1    0    0    0    0]
 [   0   11 4498    0    0    0    6    0]
 [   0    0    0 4368   82    0    0    0]
 [   0    0    0    8 4511    0    0    0]
 [   2    0    0    0    0 4500    0    5]
 [   0    0   28    6    0    0 4223   98]
 [   0    0    0    0    0    0    0 4462]]


In [128]:
print('\n')
print("Precision, Recall, F1")
print('\n')
CR=classification_report(y_test, y_pred)
print(CR)
print('\n')



Precision, Recall, F1


              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4515
           1       1.00      1.00      1.00      4434
           2       0.99      1.00      0.99      4515
           3       1.00      0.98      0.99      4450
           4       0.98      1.00      0.99      4519
           5       1.00      1.00      1.00      4507
           6       1.00      0.97      0.98      4355
           7       0.98      1.00      0.99      4462

    accuracy                           0.99     35757
   macro avg       0.99      0.99      0.99     35757
weighted avg       0.99      0.99      0.99     35757



