In [1]:
import numpy as np
import pandas as pd

In [2]:
data1 = pd.read_csv('LDAP.csv')
data2 = pd.read_csv('MSSQL.csv')
data3 = pd.read_csv('NetBIOS.csv')
data4 = pd.read_csv('Portmap.csv')
data5 = pd.read_csv('Syn.csv')
data6 = pd.read_csv('UDP.csv')
data7 = pd.read_csv('UDPLag.csv')

C:\Users\labuser.ITS\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
data1.shape

(2113234, 88)

In [4]:
data2.shape

(5775786, 88)

In [5]:
data3.shape

(3455899, 88)

In [6]:
data4.shape

(191694, 88)

In [7]:
data5.shape

(4320541, 88)

In [8]:
data6.shape

(3782206, 88)

In [9]:
data7.shape

(725165, 88)

In [10]:
data1_sample = data1.sample(500000)
data2_sample = data2.sample(500000)
data3_sample = data3.sample(500000)
data5_sample = data5.sample(500000)
data6_sample = data6.sample(500000)
data7_sample = data7.sample(500000)

In [11]:
data = pd.concat([data1_sample,data2_sample,data3_sample,data4,data5_sample,data6_sample,data7_sample], ignore_index = True)

In [12]:
data[' Label'].value_counts()

Syn        914315
UDP        573788
NetBIOS    547326
MSSQL      502144
LDAP       452101
Portmap    186960
BENIGN      13786
UDPLag       1274
Name:  Label, dtype: int64

In [13]:
data = data.drop(['Unnamed: 0'],axis = 1)
data = data.drop(['SimillarHTTP'],axis = 1)

In [14]:
data_real = data.replace(np.inf, np.nan)
data_real.isnull().sum().sum()

273462

In [15]:
data_df = data_real.dropna(axis=0)
data_df.isnull().sum().sum()

0

In [16]:
df = data_df.copy()
cat_columns = df.select_dtypes(['object']).columns
cat_columns

Index(['Flow ID', ' Source IP', ' Destination IP', ' Timestamp', ' Label'], dtype='object')

In [17]:
df[cat_columns] = df[cat_columns].astype('category')
df[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)
df
data = df
data.dtypes

Flow ID                int32
 Source IP             int16
 Source Port           int64
 Destination IP        int16
 Destination Port      int64
                      ...   
 Idle Std            float64
 Idle Max            float64
 Idle Min            float64
 Inbound               int64
 Label                  int8
Length: 86, dtype: object

In [18]:
data[' Label'].value_counts()

5    847173
6    563368
3    525880
2    484627
1    441814
4    177197
0     13630
7      1274
Name:  Label, dtype: int64

In [19]:
data= data.sample(n=len(data), random_state=1)

In [21]:
X = data.iloc[:, 0:-1].values
y = data.iloc[:, -1].values
print('length of the dataset now', len(X))

length of the dataset now 3054963


In [22]:
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
X= standardScaler.fit_transform(X)
X

array([[ 0.46617021, -0.06308787,  1.53218894, ..., -0.17522194,
        -0.15924549,  0.0652663 ],
       [ 1.41831251, -0.06308787, -1.05668733, ..., -0.17522194,
        -0.15924549,  0.0652663 ],
       [-0.33647457, -0.06308787, -0.87722872, ..., -0.17522194,
        -0.15924549,  0.0652663 ],
       ...,
       [-0.35071973, -0.06308787,  1.07154312, ..., -0.17522194,
        -0.15924549,  0.0652663 ],
       [-0.76152432, -0.06308787,  0.69648524, ..., -0.17522194,
        -0.15924549,  0.0652663 ],
       [ 1.43287157, -0.06308787, -1.05668733, ..., -0.17522194,
        -0.15924549,  0.0652663 ]])

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.67, test_size = 0.33, random_state = 42)

In [25]:
X_train.shape

(2046825, 85)

In [26]:
X_test.shape

(1008138, 85)

In [ ]:
#NN

In [28]:
#CNN algorithm libraries
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Conv1D, GlobalMaxPooling1D
from tensorflow.keras.optimizers import RMSprop

#for evaluation of trained algorithms 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [52]:
model = Sequential()

In [53]:
model.add(Dense(64, input_dim=85))
model.add(Activation('relu'))
model.add(Dropout(0.01))

In [54]:
model.add(Dense(32))
model.add(Activation('relu'))
model.add(Dropout(0.01))
model.add(Dense(8, activation="softmax"))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_17 (Dense)            (None, 64)                5504      
                                                                 
 activation_12 (Activation)  (None, 64)                0         
                                                                 
 dropout_12 (Dropout)        (None, 64)                0         
                                                                 
 dense_18 (Dense)            (None, 32)                2080      
                                                                 
 activation_13 (Activation)  (None, 32)                0         
                                                                 
 dropout_13 (Dropout)        (None, 32)                0         
                                                                 
 dense_19 (Dense)            (None, 8)                

In [55]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['acc'])

In [56]:
model.summary()
model.compile(loss='sparse_categorical_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_17 (Dense)            (None, 64)                5504      
                                                                 
 activation_12 (Activation)  (None, 64)                0         
                                                                 
 dropout_12 (Dropout)        (None, 64)                0         
                                                                 
 dense_18 (Dense)            (None, 32)                2080      
                                                                 
 activation_13 (Activation)  (None, 32)                0         
                                                                 
 dropout_13 (Dropout)        (None, 32)                0         
                                                                 
 dense_19 (Dense)            (None, 8)                

In [57]:
model.fit(X_train,y_train,batch_size=20,epochs=20,
          validation_split=0.1)

Epoch 1/20
92108/92108 [==============================] - 101s 1ms/step - loss: 0.1141 - accuracy: 0.9888 - val_loss: 0.1529 - val_accuracy: 0.9907
Epoch 2/20
92108/92108 [==============================] - 100s 1ms/step - loss: 0.1928 - accuracy: 0.9919 - val_loss: 0.1705 - val_accuracy: 0.9916
Epoch 3/20
92108/92108 [==============================] - 101s 1ms/step - loss: 0.2738 - accuracy: 0.9924 - val_loss: 0.2224 - val_accuracy: 0.9913
Epoch 4/20
92108/92108 [==============================] - 101s 1ms/step - loss: 0.4810 - accuracy: 0.9930 - val_loss: 0.9451 - val_accuracy: 0.9955
Epoch 5/20
92108/92108 [==============================] - 101s 1ms/step - loss: 0.6957 - accuracy: 0.9931 - val_loss: 0.6958 - val_accuracy: 0.9928
Epoch 6/20
92108/92108 [==============================] - 102s 1ms/step - loss: 0.6426 - accuracy: 0.9936 - val_loss: 0.4507 - val_accuracy: 0.9927
Epoch 7/20
92108/92108 [==============================] - 113s 1ms/step - loss: 0.6051 - accuracy: 0.9936 - val_

In [65]:
y_pred = model.predict(X_test)
y_pred=y_pred.argmax(axis=1)

In [59]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [60]:
rf_conf_mat = confusion_matrix(y_test, y_pred)
print("CNN Confusion: \n", rf_conf_mat)

CNN Confusion: 
 [[  4286      0      4      4     16    184      4      0]
 [    12 145558    104     20     17     31      2      0]
 [    10     63 160083      4     10     95    204      0]
 [     1      3     13 173302    224    222      2      0]
 [    46      2      0   1549  56526     77      0      0]
 [    46      1      0      0      0 279638     87      0]
 [     9      0    569      0      0    306 184339      1]
 [    16      0      0      0      0    185    263      0]]


In [61]:
print('\n')
print("Precision, Recall, F1")
print('\n')
CR=classification_report(y_test, y_pred)
print(CR)
print('\n')



Precision, Recall, F1


              precision    recall  f1-score   support

           0       0.97      0.95      0.96      4498
           1       1.00      1.00      1.00    145744
           2       1.00      1.00      1.00    160469
           3       0.99      1.00      0.99    173767
           4       1.00      0.97      0.98     58200
           5       1.00      1.00      1.00    279772
           6       1.00      1.00      1.00    185224
           7       0.00      0.00      0.00       464

    accuracy                           1.00   1008138
   macro avg       0.87      0.86      0.87   1008138
weighted avg       1.00      1.00      1.00   1008138





In [62]:
#RF

In [63]:
from sklearn.ensemble import RandomForestClassifier

In [64]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [66]:
rf_y_pred = rf.predict(X_test)

In [67]:
rf_y_pred

array([1, 2, 6, ..., 4, 2, 6], dtype=int8)

In [69]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data_y_trans = le.fit_transform(y)

In [70]:
print("Classification report for Random Forest : /n", classification_report(le.inverse_transform(y_test), le.inverse_transform(rf_y_pred)))

Classification report for Random Forest : /n               precision    recall  f1-score   support

           0       1.00      1.00      1.00      4498
           1       1.00      1.00      1.00    145744
           2       1.00      1.00      1.00    160469
           3       1.00      1.00      1.00    173767
           4       1.00      1.00      1.00     58200
           5       1.00      1.00      1.00    279772
           6       1.00      1.00      1.00    185224
           7       0.97      0.94      0.95       464

    accuracy                           1.00   1008138
   macro avg       1.00      0.99      0.99   1008138
weighted avg       1.00      1.00      1.00   1008138



In [71]:
rf_conf_mat = confusion_matrix(y_test, rf_y_pred)
print("Random Forset Confusion: \n", rf_conf_mat)

Random Forset Confusion: 
 [[  4498      0      0      0      0      0      0      0]
 [     0 145734      2      1      4      0      2      1]
 [     1      5 160454      2      4      0      3      0]
 [     0      2      0 173762      1      2      0      0]
 [     0      6      1      6  58184      2      0      1]
 [     0      2      0      0      1 279761      2      6]
 [     1      0      2      1      4      2 185208      6]
 [     0      2      1      0      4      7     14    436]]


In [72]:
acc_score = accuracy_score(y_test, rf_y_pred)
print("Accuracy score for random forest: \n ",acc_score*100)

Accuracy score for random forest: 
  99.98998153030637


In [73]:
#SVM

In [74]:
from sklearn.svm import LinearSVC

In [75]:
svm = LinearSVC(multi_class = 'ovr')
svm.fit(X_train,y_train)

C:\Users\labuser.ITS\Anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC()

In [76]:
y_pred_svm = svm.predict(X_test)

In [77]:
svm.score(X_test, y_test)

0.9852440836472784

In [78]:
print("Classification Report for Random Forest: \n ", classification_report(le.inverse_transform(y_test),le.inverse_transform(y_pred_svm)))

Classification Report for Random Forest: 
                precision    recall  f1-score   support

           0       0.96      0.97      0.97      4498
           1       0.99      1.00      1.00    145744
           2       0.98      0.94      0.96    160469
           3       0.98      0.99      0.98    173767
           4       0.99      0.99      0.99     58200
           5       1.00      1.00      1.00    279772
           6       1.00      0.99      0.99    185224
           7       0.02      0.20      0.03       464

    accuracy                           0.99   1008138
   macro avg       0.86      0.89      0.87   1008138
weighted avg       0.99      0.99      0.99   1008138



In [79]:
svm_conf_mat = confusion_matrix(y_test, y_pred_svm)
print("SVM Confusion Matrix: \n", svm_conf_mat)

SVM Confusion Matrix: 
 [[  4385      0     33     24     22     25      6      3]
 [     8 145549    116     31      0      0      0     40]
 [    91    932 150646   3382      0      1    352   5065]
 [    14    163   1090 172081    409      0      0     10]
 [    18     30     54    414  57680      0      0      4]
 [    33      1      2     15      0 279499    218      4]
 [    13      0   1783     20      0      7 183330     71]
 [    16      0      0      2      0     11    343     92]]


In [80]:
acc_score_svm = accuracy_score(y_test, y_pred_svm)
print("Accuracy Score for SVM: \n", acc_score_svm * 100)

Accuracy Score for SVM: 
 98.52440836472785


In [81]:
#decision tree

In [82]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [83]:
dt_y_pred = dt.predict(X_test)

In [84]:
print("Classification Report for Decision Tree: \n",classification_report(le.inverse_transform(y_test), le.inverse_transform(dt_y_pred)))

Classification Report for Decision Tree: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      4498
           1       1.00      1.00      1.00    145744
           2       1.00      1.00      1.00    160469
           3       1.00      1.00      1.00    173767
           4       1.00      1.00      1.00     58200
           5       1.00      1.00      1.00    279772
           6       1.00      1.00      1.00    185224
           7       1.00      1.00      1.00       464

    accuracy                           1.00   1008138
   macro avg       1.00      1.00      1.00   1008138
weighted avg       1.00      1.00      1.00   1008138



In [85]:
dt_conf_mat = confusion_matrix(y_test,dt_y_pred)
print("Decision Tree confusion: \n", dt_conf_mat)

Decision Tree confusion: 
 [[  4491      0      4      0      0      1      1      1]
 [     1 145743      0      0      0      0      0      0]
 [     0      0 160469      0      0      0      0      0]
 [     0      0      0 173767      0      0      0      0]
 [     0      0      0      1  58199      0      0      0]
 [     0      0      0      0      0 279772      0      0]
 [     0      0      0      0      0      0 185223      1]
 [     0      0      0      0      0      0      0    464]]


In [86]:
acc_score_dt = accuracy_score(y_test, dt_y_pred)
print("Accuracy score for the decision tree is ", acc_score_dt*100)

Accuracy score for the decision tree is  99.99900807230756
